// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeaXEfaebizlvRgmxB5v3LpB3C3BWmEgE',
    appId: '1:1084606644839:web:adef03fb2ddd52c9c0cac2',
    messagingSenderId: '1084606644839',
    projectId: 'studentapp-f1df1',
    authDomain: 'studentapp-f1df1.firebaseapp.com',
    storageBucket: 'studentapp-f1df1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-JeRwqkeYclgcKjrs3Hkf1Z7zm6Ctk5g',
    appId: '1:1084606644839:android:b027831fe75295dec0cac2',
    messagingSenderId: '1084606644839',
    projectId: 'studentapp-f1df1',
    storageBucket: 'studentapp-f1df1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz0u3Ki2H66cbszm2uoow8pmtzxWFOX4w',
    appId: '1:1084606644839:ios:725a80bae38724e2c0cac2',
    messagingSenderId: '1084606644839',
    projectId: 'studentapp-f1df1',
    storageBucket: 'studentapp-f1df1.appspot.com',
    iosBundleId: 'com.example.studentInfoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz0u3Ki2H66cbszm2uoow8pmtzxWFOX4w',
    appId: '1:1084606644839:ios:0c903ce01e17df09c0cac2',
    messagingSenderId: '1084606644839',
    projectId: 'studentapp-f1df1',
    storageBucket: 'studentapp-f1df1.appspot.com',
    iosBundleId: 'com.example.studentInfoApp.RunnerTests',
  );
}
